# Generated by Selenium IDE
import random

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_buh(self):
    self.driver.get("http://localhost:8000/etrivia/login")
    self.driver.find_element(By.LINK_TEXT, "Not registered? Sign in").click()
    self.driver.find_element(By.ID, "id_username").click()
    username = "dordetest" + str(random.randint(0,100000))
    self.driver.find_element(By.ID, "id_username").send_keys(username)
    self.driver.find_element(By.ID, "id_password1").click()
    self.driver.find_element(By.ID, "id_password1").send_keys("Sifta1337")
    self.driver.find_element(By.ID, "id_password2").click()
    self.driver.find_element(By.ID, "id_password2").send_keys("Sifta1337")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-button").click()


    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys(username)


    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Sifta1337")

    self.driver.find_element(By.CSS_SELECTOR, ".submit-button").click()
    self.driver.find_element(By.LINK_TEXT, "Training").click()
    self.driver.find_element(By.LINK_TEXT, "Logic Link").click()
    self.driver.find_element(By.CSS_SELECTOR, ".word:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".match:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".word:nth-child(6)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".match:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".word:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".match:nth-child(7)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".word:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".match:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".word:nth-child(7)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".match:nth-child(8)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".word:nth-child(8)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".match:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".word:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".match:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".word:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".match:nth-child(2)").click()
    self.driver.find_element(By.LINK_TEXT, "Back To Game Selection").click()
  
