# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# Mihajlo Rajic 2021/0331
class TestTestnumberhunt():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testnumberhunt(self):
    self.driver.get("http://localhost:8000/etrivia/training/numberhunt/")
    self.driver.set_window_size(697, 1080)
    self.driver.find_element(By.ID, "numberhunt_number6").click()
    self.driver.find_element(By.ID, "numberhunt_operation3").click()
    self.driver.find_element(By.ID, "numberhunt_operation5").click()
    self.driver.find_element(By.ID, "numberhunt_number5").click()
    self.driver.find_element(By.ID, "numberhunt_operation1").click()
    self.driver.find_element(By.ID, "numberhunt_number1").click()
    self.driver.find_element(By.ID, "numberhunt_operation6").click()
    self.driver.find_element(By.ID, "numberhunt_operation1").click()
    self.driver.find_element(By.ID, "numberhunt_number4").click()
    self.driver.find_element(By.ID, "numberhunt_confirm").click()
  
