# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

#Uroš Rajčić 2021/0540
class TestSecretSequencetest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_secretSequencetest(self):
    self.driver.get("http://localhost:8000/etrivia/training/secretsequence/")
    self.driver.set_window_size(2576, 1408)
    self.driver.find_element(By.CSS_SELECTOR, ".secretsequence_operation:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".secretsequence_operation:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".secretsequence_operation:nth-child(4)").click()
    element = self.driver.find_element(By.ID, "secretsequence_confirm")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "secretsequence_confirm").click()
    self.driver.find_element(By.CSS_SELECTOR, ".secretsequence_operation:nth-child(6)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".secretsequence_operation:nth-child(2)").click()
    element = self.driver.find_element(By.ID, "secretsequence_confirm")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".secretsequence_operation:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".secretsequence_operation:nth-child(1)").click()
    self.driver.find_element(By.ID, "secretsequence_confirm").click()
    element = self.driver.find_element(By.ID, "secretsequence_confirm")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element_with_offset(element, 0, 0).perform()

    self.driver.find_element(By.CSS_SELECTOR, ".secretsequence_operation:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".secretsequence_operation:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".secretsequence_operation:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".secretsequence_operation:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".secretsequence_operation:nth-child(2)").click()
    self.driver.find_element(By.ID, "secretsequence_confirm").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header-container").click()
  
