# Generated by Django 4.2.12 on 2024-05-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etrivia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsll',
            name='prompt',
            field=models.CharField(blank=True, db_column='Prompt', max_length=50, null=True),
        ),
    ]
