# Generated by Django 4.2.12 on 2024-05-14 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Etrivia', '0003_numberhunt_secretsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='idnh',
            field=models.ForeignKey(blank=True, db_column='IdHunt', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Etrivia.numberhunt'),
        ),
        migrations.AddField(
            model_name='game',
            name='idss',
            field=models.ForeignKey(blank=True, db_column='IdSecret', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Etrivia.secretsequence'),
        ),
    ]
