# Generated by Django 4.2.12 on 2024-05-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etrivia', '0004_game_idnh_game_idss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llfield',
            name='text',
        ),
        migrations.AddField(
            model_name='llfield',
            name='left',
            field=models.CharField(db_column='Left', default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='llfield',
            name='right',
            field=models.CharField(db_column='Right', default='default', max_length=50),
        ),
    ]
