# Generated by Django 4.2.12 on 2024-05-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etrivia', '0005_remove_llfield_text_llfield_left_llfield_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='timestarted',
            field=models.DateTimeField(db_column='TimeStarted', null=True),
        ),
    ]
