# Generated by Django 4.2.12 on 2024-05-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etrivia', '0006_alter_game_timestarted'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='joined',
            field=models.IntegerField(db_column='joined', default=0),
        ),
    ]
