# Generated by Django 5.0.6 on 2024-05-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etrivia', '0008_alter_result_idresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='idqow1',
            field=models.ForeignKey(blank=True, db_column='IdQOW1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Etrivia.questionsqow'),
        ),
        migrations.AlterField(
            model_name='game',
            name='idqow2',
            field=models.ForeignKey(blank=True, db_column='IdQOW2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_idqow2_set', to='Etrivia.questionsqow'),
        ),
        migrations.AlterField(
            model_name='game',
            name='idqow3',
            field=models.ForeignKey(blank=True, db_column='IdQOW3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_idqow3_set', to='Etrivia.questionsqow'),
        ),
        migrations.AlterField(
            model_name='game',
            name='idqow4',
            field=models.ForeignKey(blank=True, db_column='IdQOW4', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_idqow4_set', to='Etrivia.questionsqow'),
        ),
        migrations.AlterField(
            model_name='game',
            name='idqow5',
            field=models.ForeignKey(blank=True, db_column='IdQOW5', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_idqow5_set', to='Etrivia.questionsqow'),
        ),
    ]
