# Generated by Django 5.0.6 on 2024-05-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etrivia', '0009_alter_game_idqow1_alter_game_idqow2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretsequence',
            name='symbol1',
        ),
        migrations.RemoveField(
            model_name='secretsequence',
            name='symbol2',
        ),
        migrations.RemoveField(
            model_name='secretsequence',
            name='symbol3',
        ),
        migrations.RemoveField(
            model_name='secretsequence',
            name='symbol4',
        ),
        migrations.RemoveField(
            model_name='secretsequence',
            name='symbol5',
        ),
        migrations.RemoveField(
            model_name='secretsequence',
            name='symbol6',
        ),
        migrations.RemoveField(
            model_name='secretsequence',
            name='symbol7',
        ),
        migrations.RemoveField(
            model_name='secretsequence',
            name='symbol8',
        ),
        migrations.AddField(
            model_name='secretsequence',
            name='symbol11',
            field=models.IntegerField(db_column='Symbol11', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretsequence',
            name='symbol12',
            field=models.IntegerField(db_column='Symbol12', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretsequence',
            name='symbol13',
            field=models.IntegerField(db_column='Symbol13', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretsequence',
            name='symbol21',
            field=models.IntegerField(db_column='Symbol21', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretsequence',
            name='symbol22',
            field=models.IntegerField(db_column='Symbol22', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretsequence',
            name='symbol23',
            field=models.IntegerField(db_column='Symbol23', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretsequence',
            name='symbol24',
            field=models.IntegerField(db_column='Symbol24', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretsequence',
            name='symbol31',
            field=models.IntegerField(db_column='Symbol31', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretsequence',
            name='symbol32',
            field=models.IntegerField(db_column='Symbol32', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretsequence',
            name='symbol33',
            field=models.IntegerField(db_column='Symbol33', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretsequence',
            name='symbol34',
            field=models.IntegerField(db_column='Symbol34', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretsequence',
            name='symbol35',
            field=models.IntegerField(db_column='Symbol35', default=0),
            preserve_default=False,
        ),
    ]
