# Generated by Django 4.2.12 on 2024-05-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etrivia', '0010_remove_secretsequence_symbol1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finished',
            field=models.IntegerField(db_column='finished', default=0),
        ),
    ]
