# Generated by Django 5.0.6 on 2024-05-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etrivia', '0013_result_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llfield',
            name='left',
            field=models.CharField(db_column='Left', default='default', max_length=150),
        ),
        migrations.AlterField(
            model_name='llfield',
            name='right',
            field=models.CharField(db_column='Right', default='default', max_length=150),
        ),
        migrations.AlterField(
            model_name='questionsll',
            name='prompt',
            field=models.CharField(blank=True, db_column='Prompt', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questionsqow',
            name='correct',
            field=models.CharField(db_column='Correct', max_length=100),
        ),
        migrations.AlterField(
            model_name='questionsqow',
            name='incorrect1',
            field=models.CharField(db_column='Incorrect1', max_length=100),
        ),
        migrations.AlterField(
            model_name='questionsqow',
            name='incorrect2',
            field=models.CharField(db_column='Incorrect2', max_length=100),
        ),
        migrations.AlterField(
            model_name='questionsqow',
            name='incorrect3',
            field=models.CharField(db_column='Incorrect3', max_length=100),
        ),
        migrations.AlterField(
            model_name='questionsqow',
            name='question',
            field=models.CharField(db_column='Question', max_length=200),
        ),
    ]
